language: elixir
elixir:
  - 1.6
  - 1.7
otp_release:
  - 20.0
  - 21.0
env:
  - MIX_ENV=test VERBOSE_TESTS=true
cache:
  directories:
    - _build
    - deps
before_script:
  - epmd -daemon
  - mix deps.get
script: mix test
